name: Deploy Strapi to VPS

on:
  push:
    branches:
      - main # Ana branch'inizi belirtin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts-path: /root/.shh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Uygulamanın deploy edileceği dizine git
            cd ${{ secrets.VPS_DEPLOY_PATH }}
            
            # Gerekli dosyaları kopyalar
            git pull origin main
            
            # Gerekli bağımlılıkları yükle
            npm install
            
            # Strapi build işlemi (yeni ise, ilk kurulumu yap)
            npm run build
            
            # Strapi servisini yeniden başlat
            pm2 restart strapi || pm2 start npm --name "strapi" -- start
          EOF
