name: Estate Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/id_rsa
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0

          # Checkout a specific branch
          ref: main

      - name: Install dependencies 👨🏻‍💻
        run: npm install

      - name: Create .dotenv file
        uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          input-prefix: ""
          file-path: ".env"
          output-prefix: ""
        env:
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
          APP_KEYS: ${{ secrets.APP_KEYS }}
          HOST: ${{ secrets.HOST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
          TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
          DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_SSL: ${{ secrets.DATABASE_SSL }}

      - name: Install pm2 globally
        run: npm install pm2 -g
        shell: bash

      - name: Build Strapi app
        run: npm run build

      - name: Start Strapi app
        run: pm2 start ecosystem.config.js

      - name: Check PM2 status before
        run: pm2 status

      - name: Sync PM2
        run: pm2 save

      - name: Test SSH connection
        run: |
          ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no root@77.37.124.127 "echo 'SSH connection established'"
        shell: bash
        env:
          SSH_KEY_PATH: ~/.ssh/id_rsa
